name: "Docker 01: Build"

on:
  push:
    branches:
      - master
      - docker-*
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate the tag for current build
      run: export TAG=${GITHUB_REF#refs/*/}; echo docker.pkg.github.com/${{ github.repository }}/docker-01-build:${TAG/master/latest}
