name: "Docker 01: Build"

on:
  push:
    branches:
      - master
      - docker-*
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate tag
      run: echo docker.pkg.github.com/${{ github.repository }}/docker-01-build:${${GITHUB_REF#refs/*/}/master/latest}
