name: Hello
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello"
      env:
        REF: ${{ github.ref }}
        WORKSPACE: ${{ github.WORKSPACE }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
