name: Hello
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: ls -al ${{ github.workspace }}

    - name: save context
      run: echo ${GITHUB_CONTEXT} > /tmp/context.json
      env:
        REF: ${{ github.ref }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: read context
      run: cat /tmp/context.json

    - run: echo ${GITHUB_REF}
    - name: save ref
      run: echo ${REF#refs/*/} > /tmp/ref.txt
      env:
        REF: ${{ github.ref }}
    - name: read ref
      run: cat /tmp/ref.txt

    - name: Use "quote" 'and' `symbols`.
      run: echo nop

    - name: Install the hub command
      run: curl -LO https://github.com/github/hub/releases/download/v2.12.3/hub-darwin-amd64-2.12.3.tgz
    - run: tar xf hub-darwin-amd64-2.12.3.tgz
    - run: hub-darwin-amd64-2.12.3/bin/hub release create -a release-template.json -m 'release via actions' -t v0.0.1 v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a new release
      run: sed -e "s!PLACEHOLDER_TAG_NAME!${GITHUB_REF#refs/*/}!g" release-template.json > /tmp/release.json
    - run: cat /tmp/release.json
