name: Hello
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls -al ${{ github.workspace }}
    - name: save context
      run: echo ${GITHUB_CONTEXT} > /tmp/context.json
      env:
        TAG: ${REF##*/}
        REF: ${{ github.ref }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: read context
      run: cat /tmp/context.json
