name: xcode-02-with-docker

on:
  push:
    branches:
      - master
      - xcode-*
    tags:
      - xcode-*

jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - run: uname -a > uname.macos
      working-directory: ./working
    - run: ls -al
      working-directory: ./working
    - run: cat uname.*
      working-directory: ./working

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: uname -a > uname.ubuntu
      working-directory: ./working
    - run: ls -al
      working-directory: ./working
    - run: cat uname.*
      working-directory: ./working

  build-on-docker:
    runs-on: ubuntu-latest
    container:
      image:  node:10
    steps:
    - uses: actions/checkout@master
    - run: echo '{}' > package.json
      working-directory: ./working
    - run: npm install
      working-directory: ./working
    - run: ls -al
      working-directory: ./working
    - run: cat uname.*
      working-directory: ./working
    - run: cat package*
      working-directory: ./working
