name: xcode-02-with-docker

on:
  push:
    branches:
      - master
      - xcode-*
    tags:
      - xcode-*

jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - run: uname -a > ./dummy/uname.macos
    - publish: dummy
      artifact: Dummy
