name: xcode-02-with-docker

on:
  push:
    branches:
      - master
      - xcode-*
    tags:
      - xcode-*

jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - run: uname -a > $GITHUB_WORKSPACE/uname.macos
    - run: ls -al $GITHUB_WORKSPACE
    - run: cat $GITHUB_WORKSPACE/uname.*

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: uname -a > $GITHUB_WORKSPACE/uname.macos
    - run: ls -al $GITHUB_WORKSPACE
    - run: cat $GITHUB_WORKSPACE/uname.*

  build-on-docker:
    runs-on: ubuntu-latest
    container:
      image:  node:10
      volumes:
      - /data
    steps:
    - uses: actions/checkout@master
    - run: uname -a > $GITHUB_WORKSPACE/uname.macos
    - run: ls -al $GITHUB_WORKSPACE
    - run: cat $GITHUB_WORKSPACE/uname.*
